name 'cek-snmp'
version '0.1.1'

author ''
license ''
project_page 'https://github.com/celesteking/puppet-snmp'
source 'git://github.com/celesteking/puppet-snmp.git'
summary 'Manages SNMP daemon & client utils'
description 'Manages SNMP daemon & client utils'
dependency 'cek/fstdlib', '~0.0.3'
dependency 'puppetlabs/stdlib', '>=3.0.0'
